site_name: ASA REUSE
site_url: https://firstgambrellianempire.com/asa-wiki
nav:
  - Purpose And Initial Premise: index.md
  - Current Documentation:
    - current_documentation/software_boot_process.md
    - current_documentation/weakspots.md
  - Logged Work: 
    - blog/index.md
theme:
  palette:
    primary: blue
    scheme: default
  name: material
  features:
    - navigation.indexes
plugins:
  - search
  - blog