site_name: ASA REUSE
site_url: https://firstgambrellianempire.com/asa-wiki
nav:
  - Purpose And Initial Premise: index.md
  - Attempts:     
      - attempts/debugging_if_exploits.md
      - attempts/bootloader_breaking_exploits.md
      - attempts/reverse_engineering_rommon.md
  - Hardware:
      - hardware/board.md
      - hardware/board_if_pinouts.md
  - Software:
      - software/software_boot_process.md
      - software/memory_layout.md
  - Logged Work: 
    - blog/index.md
theme:
  palette:
    primary: blue
    scheme: default
  name: material
  features:
    - navigation.indexes
plugins:
  - search
  - blog